version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
    - 15.0.0
  - dependency-name: esbuild
    versions:
    - 0.11.13
    - 0.11.15
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: "@vitejs/plugin-react-refresh"
    versions:
    - 1.3.2
  - dependency-name: vite
    versions:
    - 2.2.1
  - dependency-name: electron
    versions:
    - 12.0.4
